<?php
/**
 * NEED2TALK - LOGIN PAGE (TAILWIND + FONTAWESOME + ALPINE)
 *
 * FLUSSO ARCHITETTIRA:
 * 1. Login form per utenti non registrati con sicurezza avanzata
 * 2. Stile - Glass-morphism + Purple theme
 * 3. Responsive design ottimizzato per migliaia di utenti
 * 4. Performance GPU-accelerated animations con Alpine.js
 * 5. Security: CSRF protection, rate limiting, form validation
 */
if (!defined('APP_ROOT')) {
    exit('Accesso negato');
}

// Ensure bootstrap is loaded for helper functions
if (!function_exists('url')) {
    require_once APP_ROOT . '/app/bootstrap.php';
}

// ENTERPRISE GALAXY: Session ALWAYS active (industry standard)
// Bootstrap always starts session for ALL requests (no conditional logic)
// GDPR: Session cookies are "strictly necessary" (no consent required)
// CSRF token automatically generated by CsrfMiddleware on GET request

// Security: Ensure user is not already logged in
if (isset($_SESSION['user_id'])) {
    header('Location: ' . url('/profile'));
    exit;
}

// Get error messages and success messages
$errors = $_SESSION['errors'] ?? [];
$success = $_SESSION['success'] ?? null;
$oldInput = $_SESSION['old_input'] ?? [];

// ENTERPRISE GALAXY: Support flash_error from redirects (e.g. cross-platform block)
$flashError = $_SESSION['flash_error'] ?? null;
unset($_SESSION['errors'], $_SESSION['success'], $_SESSION['old_input'], $_SESSION['flash_error']);

// ENTERPRISE: Support single error message from controller (e.g. invalid credentials)
$error = $error ?? null;
if (!empty($error) && empty($errors)) {
    $errors = [$error]; // Convert single error to array for consistent display
}

// ENTERPRISE GALAXY: Also support flash_error (cross-platform session conflict)
if (!empty($flashError) && empty($errors)) {
    $errors = [$flashError];
}

// ENTERPRISE V7.1: Session expired message (from AJAX 401 redirect)
if (isset($_GET['expired']) && $_GET['expired'] === '1') {
    $success = 'La tua sessione è scaduta. Effettua nuovamente l\'accesso.';
}

// Page data
$title = 'Accedi a need2talk - La tua voce alle emozioni';
$description = 'Accedi al tuo account need2talk e condividi le tue emozioni attraverso la voce. Piattaforma sicura per maggiorenni.';

// ENTERPRISE: Start output buffering for content injection
ob_start();
?>
<!-- CONTENT ONLY (Alpine.js reactive wrapper) -->
<div class="min-h-screen" x-data="loginData()">

    <!-- Background Animato - Mediterranean Calm -->
    <div class="fixed inset-0 bg-gradient-to-br from-brand-midnight via-brand-slate to-brand-midnight pointer-events-none">
        <!-- Floating particles -->
        <div class="absolute inset-0 overflow-hidden">
            <div class="absolute w-2 h-2 bg-accent-purple/30 rounded-full animate-bounce" style="top: 20%; left: 10%; animation-delay: 0s; animation-duration: 3s;"></div>
            <div class="absolute w-1 h-1 bg-energy-pink/40 rounded-full animate-bounce" style="top: 40%; left: 80%; animation-delay: 1s; animation-duration: 4s;"></div>
            <div class="absolute w-3 h-3 bg-accent-violet/20 rounded-full animate-bounce" style="top: 60%; left: 20%; animation-delay: 2s; animation-duration: 5s;"></div>
            <div class="absolute w-1 h-1 bg-cool-cyan/30 rounded-full animate-bounce" style="top: 80%; left: 70%; animation-delay: 1.5s; animation-duration: 3.5s;"></div>
            <div class="absolute w-2 h-2 bg-accent-purple/25 rounded-full animate-bounce" style="top: 30%; left: 60%; animation-delay: 0.5s; animation-duration: 4.5s;"></div>
        </div>

        <!-- Gradient overlay -->
        <div class="absolute inset-0 bg-gradient-to-t from-brand-midnight/50 to-transparent"></div>
    </div>

    <!-- Main Content -->
    <div class="relative min-h-screen flex items-center justify-center px-4 py-20">
        <div class="w-full max-w-md space-y-8">

            <!-- Header -->
            <div class="text-center">
                <!-- Logo animato -->
                <div class="flex justify-center mb-6">
                    <div class="relative w-24 h-24">
                        <div class="absolute inset-0 bg-gradient-to-br from-purple-600 to-pink-600 rounded-3xl shadow-xl shadow-purple-500/30 hover:shadow-purple-500/50 transition-all duration-300"></div>
                        <picture>
                            <source srcset="<?php echo asset('img/logo-192.webp'); ?>" type="image/webp">
                            <img src="<?php echo asset('img/logo-192.png'); ?>"
                                 alt="need2talk Logo"
                                 class="absolute inset-0 w-full h-full rounded-3xl object-cover"
                                 loading="lazy"
                                 decoding="async"
                                 width="96"
                                 height="96">
                        </picture>

                        <!-- Cerchi concentrici pulsanti -->
                        <div class="absolute inset-0 rounded-full border-2 border-pink-500/60 animate-ping"></div>
                        <div class="absolute -inset-2 rounded-full border border-purple-500/40 animate-ping" style="animation-delay: 0.5s; animation-duration: 2s;"></div>
                    </div>
                </div>

                <h1 style="color: #ffffff; -webkit-text-fill-color: transparent; -webkit-background-clip: text; background-clip: text;" class="text-4xl md:text-5xl font-bold mb-4 bg-gradient-to-r from-accent-violet via-accent-purple to-accent-violet">
                    Fai sentire la tua voce
                </h1>
                <p class="text-neutral-silver text-lg mb-8">
                    Il tuo spazio sicuro per esprimere emozioni
                </p>
            </div>

            <!-- Form di Login -->
            <div class="bg-brand-charcoal backdrop-blur-lg rounded-2xl p-8 border border-accent-purple/20 shadow-2xl shadow-accent-purple/10">

                <!-- ENTERPRISE GALAXY: Google OAuth Login Button -->
                <div class="mb-6">
                    <a href="<?php echo url('auth/google'); ?>"
                       class="w-full bg-gray-900 hover:bg-gray-800 font-semibold py-4 px-6 rounded-xl transition-all duration-300 transform hover:scale-105 shadow-lg border border-gray-700 hover:border-gray-600 focus:outline-none focus:ring-2 focus:ring-accent-purple focus:ring-offset-2 focus:ring-offset-brand-charcoal group flex items-center justify-center"
                       style="color: #ffffff !important;">
                        <!-- Google Logo (Official Colors) -->
                        <svg class="w-5 h-5 mr-3" viewBox="0 0 24 24">
                            <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
                            <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
                            <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
                            <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
                        </svg>
                        <span style="color: #ffffff !important;">Continua con Google</span>
                    </a>
                </div>

                <!-- Divider -->
                <div class="relative mb-6">
                    <div class="absolute inset-0 flex items-center">
                        <div class="w-full border-t border-gray-600"></div>
                    </div>
                    <div class="relative flex justify-center text-sm">
                        <span class="px-4 bg-brand-charcoal text-gray-400">oppure</span>
                    </div>
                </div>

                <form method="POST" action="<?php echo url('auth/login'); ?>" class="space-y-6" id="loginForm" @submit="handleSubmit">
                    <?php if (class_exists('Need2Talk\\Middleware\\CsrfMiddleware')) { ?>
                        <?= Need2Talk\Middleware\CsrfMiddleware::tokenInput() ?>
                    <?php } ?>

                    <!-- ENTERPRISE GALAXY: reCAPTCHA v3 token (invisible) -->
                    <input type="hidden" name="recaptcha_token" id="recaptchaToken">

                    <!-- Success Message (dopo reset password o altre operazioni) -->
                    <?php if (!empty($success)) { ?>
                        <div class="bg-green-900/20 border border-green-500/50 rounded-xl p-4 animate-pulse">
                            <div class="flex items-center mb-2">
                                <?= icon('check-circle', 'w-5 h-5 text-green-400 mr-3') ?>
                                <h3 class="font-semibold text-green-300">Operazione completata</h3>
                            </div>
                            <p class="text-sm text-green-200 ml-2">
                                <?= icon('arrow-right', 'w-4 h-4 text-green-400 mr-2') ?>
                                <?= htmlspecialchars($success) ?>
                            </p>
                        </div>
                    <?php } ?>

                    <!-- Error Messages -->
                    <?php if (!empty($errors)) { ?>
                        <div class="bg-energy-magenta/10 border border-energy-magenta/50 rounded-xl p-4 animate-pulse">
                            <div class="flex items-center mb-2">
                                <?= icon('exclamation-triangle', 'w-5 h-5 text-energy-magenta mr-3') ?>
                                <h3 class="font-semibold text-red-300">
                                    <?php echo count($errors) === 1 ? 'Errore' : 'Errori di accesso' ?>
                                </h3>
                            </div>
                            <?php if (count($errors) === 1) { ?>
                                <!-- Single error: Display inline -->
                                <p class="text-sm text-red-200 ml-2">
                                    <?= icon('times-circle', 'w-5 h-5 text-energy-magenta mr-2') ?>
                                    <?php echo htmlspecialchars($errors[0]) ?>
                                </p>
                            <?php } else { ?>
                                <!-- Multiple errors: Display as list -->
                                <ul class="text-sm text-red-200 space-y-1 ml-2">
                                    <?php foreach ($errors as $err) { ?>
                                        <li class="flex items-center">
                                            <?= icon('arrow-right', 'w-4 h-4 text-energy-magenta mr-2') ?>
                                            <?php echo htmlspecialchars($err) ?>
                                        </li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </div>
                    <?php } ?>

                    <!-- Email -->
                    <div class="space-y-2">
                        <label for="email" class="block text-sm font-semibold text-accent-violet mb-2 flex items-center">
                            <?= icon('envelope', 'w-5 h-5 text-accent-purple mr-2') ?>
                            Email
                        </label>
                        <div class="relative group">
                            <input
                                id="email"
                                name="email"
                                type="email"
                                required
                                value="<?php echo htmlspecialchars($oldInput['email'] ?? ''); ?>"
                                class="w-full px-4 py-4 pl-12 bg-brand-midnight/50 border border-neutral-darkGray rounded-xl text-neutral-white placeholder-neutral-gray focus:border-accent-purple focus:ring-2 focus:ring-accent-purple/30 focus:bg-white focus:text-gray-900 transition-all duration-300 group-hover:border-accent-purple/50"
                                placeholder="la-tua-email@esempio.com"
                                autocomplete="email"
                                x-model="formData.email"
                                @blur="validateEmail"
                            >
                            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                <?= icon('envelope', 'w-5 h-5 text-accent-purple group-focus-within:text-gray-900 transition-colors') ?>
                            </div>
                        </div>
                    </div>

                    <!-- Password -->
                    <div class="space-y-2">
                        <label for="password" class="block text-sm font-semibold text-accent-violet mb-2 flex items-center">
                            <?= icon('lock', 'w-5 h-5 text-accent-purple mr-2') ?>
                            Password
                        </label>
                        <div class="relative group">
                            <input
                                id="password"
                                name="password"
                                :type="showPassword ? 'text' : 'password'"
                                required
                                class="w-full px-4 py-4 pl-12 pr-12 bg-brand-midnight/50 border border-neutral-darkGray rounded-xl text-neutral-white placeholder-neutral-gray focus:border-accent-purple focus:ring-2 focus:ring-accent-purple/30 focus:bg-white focus:text-gray-900 transition-all duration-300 group-hover:border-accent-purple/50"
                                placeholder="La tua password segreta"
                                autocomplete="current-password"
                                x-model="formData.password"
                            >
                            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                <?= icon('lock', 'w-5 h-5 text-accent-purple group-focus-within:text-gray-900 transition-colors') ?>
                            </div>
                            <button
                                type="button"
                                @click="showPassword = !showPassword"
                                :aria-label="showPassword ? 'Nascondi password' : 'Mostra password'"
                                class="absolute inset-y-0 right-0 pr-3 flex items-center text-neutral-gray group-focus-within:text-gray-900 hover:text-accent-purple transition-colors"
                            >
                                <span x-show="showPassword" x-cloak><?= icon('eye-slash', 'w-5 h-5') ?></span>
                                <span x-show="!showPassword" x-cloak><?= icon('eye', 'w-5 h-5') ?></span>
                            </button>
                        </div>
                    </div>

                    <!-- Remember me e Forgot password -->
                    <div class="flex items-center justify-between">
                        <div class="flex items-center">
                            <input
                                id="remember"
                                name="remember"
                                type="checkbox"
                                class="w-4 h-4 text-accent-purple bg-brand-midnight border-neutral-darkGray rounded focus:ring-accent-purple focus:ring-2"
                                x-model="formData.remember"
                            >
                            <label for="remember" class="ml-2 text-sm text-neutral-silver cursor-pointer hover:text-accent-purple transition-colors">
                                Ricordami
                            </label>
                        </div>

                        <div class="text-sm">
                            <a href="<?php echo url('forgot-password'); ?>" class="text-accent-purple hover:text-accent-violet transition-colors flex items-center group">
                                <span>Password dimenticata?</span>
                                <?= icon('arrow-right', 'w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform') ?>
                            </a>
                        </div>
                    </div>

                    <!-- Resend verification email link -->
                    <div class="text-center">
                        <a href="<?php echo url('auth/resend-verification-form'); ?>" class="text-sm text-neutral-silver hover:text-accent-purple transition-colors flex items-center justify-center group">
                            <?= icon('envelope', 'w-4 h-4 text-accent-purple mr-2') ?>
                            <span>Email di verifica non ricevuta?</span>
                            <?= icon('arrow-right', 'w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform') ?>
                        </a>
                    </div>

                    <!-- Submit Button -->
                    <div class="space-y-6">
                        <button
                            type="submit"
                            class="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white font-semibold py-4 px-6 rounded-xl transition-all duration-300 transform hover:scale-105 shadow-lg shadow-purple-500/25 focus:outline-none focus:ring-2 focus:ring-accent-purple focus:ring-offset-2 focus:ring-offset-white disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none group"
                            :disabled="isSubmitting"
                        >
                            <span class="flex items-center justify-center" x-show="!isSubmitting">
                                <?= icon('microphone', 'w-5 h-5 mr-2 group-hover:animate-pulse') ?>
                                Entra e fai sentire la tua voce
                            </span>
                            <span class="flex items-center justify-center" x-show="isSubmitting">
                                <?= icon('spinner', 'w-5 h-5 animate-spin mr-2') ?>
                                Connessione in corso...
                            </span>
                        </button>

                    </div>
                </form>
            </div>

            <!-- Register Link -->
            <div class="text-center space-y-6">
                <div class="flex items-center justify-center space-x-2 text-neutral-silver">
                    <span>Non hai ancora un account?</span>
                    <a href="<?php echo url('auth/register'); ?>" class="text-accent-purple hover:text-accent-violet font-semibold transition-colors inline-flex items-center group">
                        Registrati gratis
                        <?= icon('arrow-right', 'w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform') ?>
                    </a>
                </div>

                <!-- Emozioni disponibili -->
                <div class="flex justify-center space-x-4 text-2xl opacity-60">
                    <span title="Felicità"><?= icon('laugh', 'text-accent-lavender hover:scale-125 transition-transform cursor-pointer') ?></span>
                    <span title="Eccitazione"><?= icon('star', 'w-5 h-5 text-accent-purple hover:scale-125 transition-transform cursor-pointer') ?></span>
                    <span title="Amore"><?= icon('heart', 'w-5 h-5 text-energy-pink hover:scale-125 transition-transform cursor-pointer') ?></span>
                    <span title="Gratitudine"><?= icon('hands', 'w-5 h-5 text-cool-cyan hover:scale-125 transition-transform cursor-pointer') ?></span>
                    <span title="Tristezza"><?= icon('sad-tear', 'w-5 h-5 text-accent-violet hover:scale-125 transition-transform cursor-pointer') ?></span>
                    <span title="Rabbia"><?= icon('angry', 'w-5 h-5 text-energy-magenta hover:scale-125 transition-transform cursor-pointer') ?></span>
                </div>
            </div>

            <!-- Features -->
            <div class="text-center mt-8 space-y-4">
                <p class="text-neutral-silver text-sm font-medium">Unisciti a migliaia di voci autentiche</p>
                <div class="grid grid-cols-1 gap-3 max-w-sm mx-auto">
                    <div class="flex items-center text-sm text-neutral-white bg-brand-charcoal/30 rounded-lg p-3 border border-neutral-darkGray/30">
                        <div class="w-8 h-8 rounded-full bg-cool-cyan/20 flex items-center justify-center mr-3 flex-shrink-0">
                            <?= icon('microphone', 'w-4 h-4 text-cool-cyan') ?>
                        </div>
                        <span>Registra i tuoi sfoghi in completo anonimato</span>
                    </div>
                    <div class="flex items-center text-sm text-neutral-white bg-brand-charcoal/30 rounded-lg p-3 border border-neutral-darkGray/30">
                        <div class="w-8 h-8 rounded-full bg-accent-purple/20 flex items-center justify-center mr-3 flex-shrink-0">
                            <?= icon('headphones', 'w-4 h-4 text-accent-purple') ?>
                        </div>
                        <span>Ascolta le emozioni di chi ti capisce</span>
                    </div>
                    <div class="flex items-center text-sm text-neutral-white bg-brand-charcoal/30 rounded-lg p-3 border border-neutral-darkGray/30">
                        <div class="w-8 h-8 rounded-full bg-energy-pink/20 flex items-center justify-center mr-3 flex-shrink-0">
                            <?= icon('heart', 'w-4 h-4 text-energy-pink') ?>
                        </div>
                        <span>Connettiti con una community che ti ascolta</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div> <!-- End Alpine.js reactive wrapper -->

<!-- PAGE-SPECIFIC Alpine.js Login Data -->
<script nonce="<?= csp_nonce() ?>">
function loginData() {
    return {
        formData: {
            email: '<?php echo htmlspecialchars($oldInput['email'] ?? ''); ?>',
            password: '',
            remember: false
        },
        showPassword: false,
        isSubmitting: false,

        init() {
            // Auto-focus on email field if empty
            if (!this.formData.email) {
                this.$nextTick(() => {
                    document.getElementById('email').focus();
                });
            }

            // PREFETCH: Handled centrally by navbar-guest.php (no duplicates)
        },

        // Form validation and submission
        handleSubmit(event) {
            const email = this.formData.email.trim();
            const password = this.formData.password;

            // Basic validation
            if (!email || !password) {
                event.preventDefault();
                alert('Tutti i campi sono obbligatori');
                return false;
            }

            // Email validation
            const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            if (!emailPattern.test(email)) {
                event.preventDefault();
                alert('Inserisci un indirizzo email valido');
                return false;
            }

            // Set loading state
            this.isSubmitting = true;

            // Re-enable after timeout in case of error
            setTimeout(() => {
                this.isSubmitting = false;
            }, 10000);
        },

        // Email validation
        validateEmail() {
            const email = this.formData.email.trim();
            const emailField = document.getElementById('email');
            const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

            if (email && !emailPattern.test(email)) {
                emailField.classList.add('border-energy-magenta');
                emailField.classList.remove('border-green-400');
            } else if (email) {
                emailField.classList.remove('border-energy-magenta');
                emailField.classList.add('border-green-400');
            }
        },

    }
}
</script>

<!-- ENTERPRISE GALAXY: reCAPTCHA v3 Script (Conditional - only if needed) -->
<?php
// Check if reCAPTCHA is required for this IP (after 3 failed attempts)
$recaptchaService = new \Need2Talk\Services\RecaptchaService();
$showRecaptcha = $recaptchaService->isRequiredForLogin();
$recaptchaSiteKey = $recaptchaService->getSiteKey();
?>

<?php if ($showRecaptcha): ?>
<script src="https://www.google.com/recaptcha/api.js?render=<?= $recaptchaSiteKey ?>"></script>
<script nonce="<?= csp_nonce() ?>">
// ENTERPRISE GALAXY: reCAPTCHA v3 Integration (Conditional for Login)
document.addEventListener('DOMContentLoaded', function() {
    const loginForm = document.getElementById('loginForm');
    if (!loginForm) return;

    loginForm.addEventListener('submit', function(e) {
        e.preventDefault();

        grecaptcha.ready(function() {
            grecaptcha.execute('<?= $recaptchaSiteKey ?>', {action: 'login'})
                .then(function(token) {
                    // Populate hidden field
                    document.getElementById('recaptchaToken').value = token;
                    // Submit form
                    loginForm.submit();
                })
                .catch(function(error) {
                    console.error('reCAPTCHA error:', error);
                    alert('Errore di sicurezza. Ricarica la pagina e riprova.');
                });
        });
    });
});
</script>
<?php endif; ?>

<?php
$content = ob_get_clean();
require APP_ROOT . '/app/Views/layouts/guest.php';
?>